version: '3.1'
services:
  db:
    image: 'database-postgresql'
    build: .
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - "./database:/var/lib/postgresql/data"
    env_file:
      - ../src/core/env/dev.env
    networks:
      - net_service

networks:
  net_service: